FROM bitnami/spark:3.5.0

USER root

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY src/ /app/src/

WORKDIR /app

ENV PYTHONPATH=/app

CMD ["python", "-m", "src.consumer"]
